### ISSUE TITLE
keepwork 海外版本部署

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/devops#1]
### 背景

xizhi： 6月1日之前， 需要我们这里能够在Amazon架设keepwork服务器。 海外用户从Amazon访问。 这个需要想一个方案。 最理想的是，两边数据是同步的，域名不变。 

### 目标
在Amazon上假设KeepWork服务器，海外用户从Amazon访问。

### 指标

> 讨论后再定 @DreamAndDead

**Comment by DreamAndDead** [comment]
可以先咨询一下CDN厂商，有没有国外服务器节点。如果只是为了国外用户访问快速，修改CDN比再搭建一套要简单

**Comment by leopoldchen** [comment]
目前已确定要亚马逊云单独部署（en.keepwork.com)，可以先做研究，先购买云服务。
另外，需要解决的一个问题是海外ip登录KeepWork.com 要自动跳转到海外版本服务器。

**Comment by DreamAndDead** [comment]
steps
- 统计所需要部署的服务
- 先购买两台服务器，测试网络连通性（后期根据需要再添加）

问题
- 海外ip登录，自动连接海外服务
- jenkins master/slave 网络连接问题
- 中转部署需要的docker hub

**Comment by DreamAndDead** [comment]
amazon ec2 机器类型
https://aws.amazon.com/cn/ec2/instance-types/

**Comment by DreamAndDead** [comment]
根据 @Xuntian  的提示，购买阿里云的海外服务器，也是一个选择

![image](https://user-images.githubusercontent.com/5028822/39804698-5708ef6c-53a7-11e8-9afc-61321dc65b84.png)

**Comment by DreamAndDead** [comment]
从内部区分环境的方案
http://keepwork.com/dreamanddead/opsway/keepwork-i18n

**Comment by DreamAndDead** [comment]
- 先在内部部署release环境，供开发调试
- 根据内部服务要求，度量相应需要的机器资源数量
- 购买服务器，连通内部release发布到外部server的过程

**Comment by DreamAndDead** [comment]
对于海外版，大致做了如下规划
http://keepwork.com/dreamanddead/opsway/keepwork-i18n

**Comment by leopoldchen** [comment]
@LiXizhi 

海外版CDN的问题请考虑一下

**Comment by leopoldchen** [comment]
可以考虑基于现有国内资源部署一下en.keepwork.com。目前已知的版本区别有：
1. 第三方登录调整为facebook、Google等
2. 取消实名验证
3. 取消关键字审核

**Comment by DreamAndDead** [comment]
目前已经
- 申请建立了虚拟机
- 走通ci流程
- 部署了 wikicraft keepwork nginx 所在的web节点

TODO
- 部署ES
- 部署gitlab

**Comment by DreamAndDead** [comment]
在内网部署 stage 环境的海外版
- keepwork, wikicraft 部署在虚拟机的docker
- es, gitlab 部署在 k8s 集群中


目前 working on 的问题是
- nginx 转发与 k8s ingress 的协调 @Xuntian 
- 将 gitlab 页面服务，也归属于 api.keepwork.com/git 下

**Comment by DreamAndDead** [comment]
目前待协调
- stage环境将 esGateway 加入 k8s 集群，使整个环境运作起来
- 正式环境还未部署 esGateway
