### ISSUE TITLE
gitlab 性能测试及调优

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/devops#5]
1. 整理测试用例
1. 部署测试环境
2. jmeter 模板
3. 测试报告（将来可以拿来做对比）
4. 测试报告分析

**Comment by DreamAndDead** [comment]
初步测试计划

http://keepwork.com/dreamanddead/opsway/gitlab-test-plan

**Comment by leopoldchen** [comment]
1. 先搭建单机gitlab，供调试jmeter模板
2. 按计划部署测试环境
3. 准备jmeter分布式（计划6台client，1台master，5台slave）
4. 核对jmeter模板
5. 测试执行
6. 结合测试报告分析，给出改进意见
7. loop 5

**Comment by DreamAndDead** [comment]
目前测试环境初步建立

- grafana地址：   http://10.28.18.9:3000
- gitlab地址：   http://10.28.18.8:80    root:rootroot


收集了jmeter, gitlab, gitlab docker三方面的数据，对应influxdb中的数据库
- jmeter -> jmeter & graphite  (两种数据统计方式)
- gitlab -> gitlab
- gitlab docker -> cadvisor


进一步
- jmeter分布式有待搭建
- 数据条目的含义有待分析

**Comment by DreamAndDead** [comment]
完成昨天TODO部分
- jmeter分布式搭建
- metric数据分析

具体见 https://github.com/tatfook/perf-test/tree/master/env/collector

@Sandu1213
