### ISSUE TITLE
Keepwork API Gateway 

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/devops#7]
需要先做一下research，基本可以敲定使用Kong来做Api gateway服务

**Comment by DreamAndDead** [comment]
kong 在 nginx 上构建了一层，将 nginx 的概念抽象成了资源类型。
目前版本还较低，0.13，还有可期待的空间。

在本机使用 docker 测试了一下，感觉还可以，admin interface 只有 rest api 的形式。

目前正在将其部署到 k8s 集群中，遇到了内部 dns 的问题，似乎无解，浏览所有相关 issue，
其中的 dns 组件不成熟，等待后续其版本升级。

计划再了解一些 k8s 内部的原理，再回来定位解决。

**Comment by leopoldchen** [comment]
考虑直接使用nodejs自建api gateway，我先做一下research

**Comment by leopoldchen** [comment]
https://cn.aliyun.com/product/apigateway?spm=5176.8142029.388261.285.715c4636wRT8p1
